# NOTE(bja, 2017-11) travis-ci dosen't support python language builds
#  on mac os. As a work around, we declare as a 'generic', use built-in
#  python on linux, and manually install python with homebrew on osx.

language: python
os: linux
python: 
  - "2.7"
  - "3.6"
matrix:
  include:
  - os: osx
    language: generic
    before_install:
      # NOTE(bja, 2017-11) update is slow, 2.7.12 installed by default, good enough!
      # - brew update
      # - brew outdated python2 || brew upgrade python2
      - virtualenv env -p python2
      - source env/bin/activate
install:
  - pip install -r test/requirements.txt
script:
  - cd test; make test
#  - cd test; make lint
after_success:
  - cd test; make coverage
  - cd test; coveralls
  