language: python
os: linux
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install -r test/requirements.txt
before_script:
  - git --version
script:
  - cd test; make test
  - cd test; make lint
after_success:
  - cd test; make coverage
  - cd test; coveralls
